//interrupt number definitions
//used in the interrupt handler

//define the value used to indicate an unsupported/unimplemented interrupt as -1
#define VAL_INT_UNIMPLEMENTED 0xFFFFFFFF

#define VAL_INT0 VAL_INT_UNIMPLEMENTED
#define VAL_INT1 VAL_INT_UNIMPLEMENTED
#define VAL_INT2 VAL_INT_UNIMPLEMENTED
#define VAL_INT3 VAL_INT_UNIMPLEMENTED
#define VAL_INT4 VAL_INT_UNIMPLEMENTED
#define VAL_INT5 VAL_INT_UNIMPLEMENTED
#define VAL_INT6 VAL_INT_UNIMPLEMENTED
#define VAL_INT7 VAL_INT_UNIMPLEMENTED
#define VAL_INT8 VAL_INT_UNIMPLEMENTED
#define VAL_INT9 VAL_INT_UNIMPLEMENTED
#define VAL_INT10 VAL_INT_UNIMPLEMENTED
#define VAL_INT11 VAL_INT_UNIMPLEMENTED
#define VAL_INT12 VAL_INT_UNIMPLEMENTED
#define VAL_INT13 VAL_INT_UNIMPLEMENTED
#define VAL_INT14 VAL_INT_UNIMPLEMENTED
#define VAL_INT15 VAL_INT_UNIMPLEMENTED
#define VAL_INT16 VAL_INT_UNIMPLEMENTED
#define VAL_INT17 VAL_INT_UNIMPLEMENTED
#define VAL_INT18 VAL_INT_UNIMPLEMENTED
#define VAL_INT19 VAL_INT_UNIMPLEMENTED
#define VAL_INT20 VAL_INT_UNIMPLEMENTED
#define VAL_INT21 VAL_INT_UNIMPLEMENTED
#define VAL_INT22 VAL_INT_UNIMPLEMENTED
#define VAL_INT23 VAL_INT_UNIMPLEMENTED
#define VAL_INT24 VAL_INT_UNIMPLEMENTED
#define VAL_INT25 VAL_INT_UNIMPLEMENTED
#define VAL_INT26 VAL_INT_UNIMPLEMENTED
#define VAL_INT27 VAL_INT_UNIMPLEMENTED
#define VAL_INT28 VAL_INT_UNIMPLEMENTED
#define VAL_INT29 VAL_INT_UNIMPLEMENTED
#define VAL_INT30 VAL_INT_UNIMPLEMENTED
#define VAL_INT31 VAL_INT_UNIMPLEMENTED
#define VAL_INT32 VAL_INT_UNIMPLEMENTED
#define VAL_INT128 VAL_INT_UNIMPLEMENTED
#define VAL_WINCALLGATE VAL_INT_UNIMPLEMENTED
#define VAL_NIXCALLGATE VAL_INT_UNIMPLEMENTED
